tbank.api.base.url=https://invest-public-api.tbank.ru/rest
tbank.token=t.NPirmUIdn5puqKCqo6wxwBIFtdCBMhICagSFmhUZ-OTGbxKpkU8DAwBRSF6tm3mUT1jFMTcxlHSMr-EEpsaKnQ
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=Java521;trustServerCertificate=true;
spring.datasource.username=UserJava521
spring.datasource.password=UserJava521
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
server.port=80
server.host=top
server.address=0.0.0.0
spring.session.jdbc.initialize-schema=never
spring.session.store-type=none
spring.session.jdbc.table-name=SPRING_SESSION
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
